import ts5 from "../assets/img/banner/ts5.png";
import ts6 from "../assets/img/banner/ts6.png";
import ts7 from "../assets/img/banner/ts7.png";
import ts8 from "../assets/img/banner/ts8.png";

export const images = [
  { id: 1, text: "Web Application Development" },
  { text: " - " },
  { id: 2, text: "Full Stack Development" },
  { text: " - " },
  { id: 3, text: "Frontend Development" },
  { text: " - " },
  { id: 4, text: "Backend Development" },
  { text: " - " },
  { id: 5, text: "API Development" },
  { text: " - " },
  { id: 6, text: "Database Design & Management" },
  { text: " - " },
  { id: 7, text: "Custom Software Development" },
  { text: " - " },
  { id: 8, text: "Cloud Integration Services" },
  { text: " - " },
  { id: 9, text: "Authentication & Authorization Systems" },
  { text: " - " },
  { id: 10, text: "Real Time Application Development" },
  { text: " - " },
  { id: 11, text: "Admin Dashboard Development" },
  { text: " - " },
  { id: 12, text: "Responsive UI Development" },
  { text: " - " },
  { id: 13, text: "Third Party API Integration" },
  { text: " - " },
  { id: 14, text: "Payment Gateway Integration" },
  { text: " - " },
  { id: 15, text: "Deployment & Hosting Services" },
  { text: " - " },
];

export const images2 = [
  { id: 1, text: "25+ International Clients" },
  { text: " - " },
  { id: 2, text: "20+ Live Projects" },
  { text: " - " },
  { id: 3, text: "Scalable Web Apps" },
  { text: " - " },
  { id: 4, text: "Production-Ready Code" },
  { text: " - " },
  { id: 5, text: "Cross-Platform Expertise" },
  { text: " - " },
  { id: 6, text: "Secure Integrations" },
  { text: " - " },
  { id: 7, text: "Clean UI/UX" },
  { text: " - " },
  { id: 8, text: "Rapid Prototyping" },
  { text: " - " },
  { id: 9, text: "Agile Development" },
  { text: " - " },
  { id: 10, text: "API Integrations" },
  { text: " - " },
  { id: 11, text: "Cloud Deployments" },
  { text: " - " },
  { id: 12, text: "Client-Focused Delivery" },
  { text: " - " },
  { id: 13, text: "Team Collaboration" },
  { text: " - " },
  { id: 14, text: "Performance Optimization" },
  { text: " - " },
  { id: 15, text: "Full-Stack Solutions" },
  { text: " - " },
];
